
package de.tu.dresden.quasy.webservices.omiotis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SRWS", targetNamespace = "http://sr.hua.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SRWS {


    /**
     * 
     * @param terms
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPairsForTerms", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTerms")
    @ResponseWrapper(localName = "getAllPairsForTermsResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTermsResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllPairsForTermsRequest", output = "http://sr.hua.org/SRWS/getAllPairsForTermsResponse")
    public String getAllPairsForTerms(
        @WebParam(name = "terms", targetNamespace = "")
        String terms);

    /**
     * 
     * @param t1
     * @param o1
     * @param p1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWordnetRank", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetWordnetRank")
    @ResponseWrapper(localName = "getWordnetRankResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetWordnetRankResponse")
    @Action(input = "http://sr.hua.org/SRWS/getWordnetRankRequest", output = "http://sr.hua.org/SRWS/getWordnetRankResponse")
    public int getWordnetRank(
        @WebParam(name = "t1", targetNamespace = "")
        String t1,
        @WebParam(name = "p1", targetNamespace = "")
        int p1,
        @WebParam(name = "o1", targetNamespace = "")
        long o1);

    /**
     * 
     * @param terms
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllGlossPairsForTerms", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllGlossPairsForTerms")
    @ResponseWrapper(localName = "getAllGlossPairsForTermsResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllGlossPairsForTermsResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllGlossPairsForTermsRequest", output = "http://sr.hua.org/SRWS/getAllGlossPairsForTermsResponse")
    public String getAllGlossPairsForTerms(
        @WebParam(name = "terms", targetNamespace = "")
        String terms);

    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGlossForSense", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetGlossForSense")
    @ResponseWrapper(localName = "getGlossForSenseResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetGlossForSenseResponse")
    @Action(input = "http://sr.hua.org/SRWS/getGlossForSenseRequest", output = "http://sr.hua.org/SRWS/getGlossForSenseResponse")
    public String getGlossForSense(
        @WebParam(name = "input", targetNamespace = "")
        String input);

    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSensesForTerm", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllSensesForTerm")
    @ResponseWrapper(localName = "getAllSensesForTermResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllSensesForTermResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllSensesForTermRequest", output = "http://sr.hua.org/SRWS/getAllSensesForTermResponse")
    public String getAllSensesForTerm(
        @WebParam(name = "input", targetNamespace = "")
        String input);

    /**
     * 
     * @param lemma
     * @param offset
     * @param pos
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllWordsForSense", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllWordsForSense")
    @ResponseWrapper(localName = "getAllWordsForSenseResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllWordsForSenseResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllWordsForSenseRequest", output = "http://sr.hua.org/SRWS/getAllWordsForSenseResponse")
    public String getAllWordsForSense(
        @WebParam(name = "lemma", targetNamespace = "")
        String lemma,
        @WebParam(name = "pos", targetNamespace = "")
        int pos,
        @WebParam(name = "offset", targetNamespace = "")
        long offset);

    /**
     * 
     * @param lemma
     * @param offset
     * @param pos
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExtendedSynsetForSense", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetExtendedSynsetForSense")
    @ResponseWrapper(localName = "getExtendedSynsetForSenseResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetExtendedSynsetForSenseResponse")
    @Action(input = "http://sr.hua.org/SRWS/getExtendedSynsetForSenseRequest", output = "http://sr.hua.org/SRWS/getExtendedSynsetForSenseResponse")
    public String getExtendedSynsetForSense(
        @WebParam(name = "lemma", targetNamespace = "")
        String lemma,
        @WebParam(name = "pos", targetNamespace = "")
        int pos,
        @WebParam(name = "offset", targetNamespace = "")
        long offset);

    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPairsForTermsPMI", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTermsPMI")
    @ResponseWrapper(localName = "getAllPairsForTermsPMIResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTermsPMIResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllPairsForTermsPMIRequest", output = "http://sr.hua.org/SRWS/getAllPairsForTermsPMIResponse")
    public String getAllPairsForTermsPMI(
        @WebParam(name = "input", targetNamespace = "")
        String input);

    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPairsForTermsGPMI", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTermsGPMI")
    @ResponseWrapper(localName = "getAllPairsForTermsGPMIResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTermsGPMIResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllPairsForTermsGPMIRequest", output = "http://sr.hua.org/SRWS/getAllPairsForTermsGPMIResponse")
    public String getAllPairsForTermsGPMI(
        @WebParam(name = "input", targetNamespace = "")
        String input);

    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPairsForTermsIDFPMI", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTermsIDFPMI")
    @ResponseWrapper(localName = "getAllPairsForTermsIDFPMIResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllPairsForTermsIDFPMIResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllPairsForTermsIDFPMIRequest", output = "http://sr.hua.org/SRWS/getAllPairsForTermsIDFPMIResponse")
    public String getAllPairsForTermsIDFPMI(
        @WebParam(name = "input", targetNamespace = "")
        String input);

    /**
     * 
     * @param word
     * @param offset
     * @param pos
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLemmaForWordPosOffset", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetLemmaForWordPosOffset")
    @ResponseWrapper(localName = "getLemmaForWordPosOffsetResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetLemmaForWordPosOffsetResponse")
    @Action(input = "http://sr.hua.org/SRWS/getLemmaForWordPosOffsetRequest", output = "http://sr.hua.org/SRWS/getLemmaForWordPosOffsetResponse")
    public String getLemmaForWordPosOffset(
        @WebParam(name = "word", targetNamespace = "")
        String word,
        @WebParam(name = "pos", targetNamespace = "")
        String pos,
        @WebParam(name = "offset", targetNamespace = "")
        String offset);

    /**
     * 
     * @param lemma1
     * @param lemma2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSRForPairOfLemmas", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetSRForPairOfLemmas")
    @ResponseWrapper(localName = "getSRForPairOfLemmasResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetSRForPairOfLemmasResponse")
    @Action(input = "http://sr.hua.org/SRWS/getSRForPairOfLemmasRequest", output = "http://sr.hua.org/SRWS/getSRForPairOfLemmasResponse")
    public double getSRForPairOfLemmas(
        @WebParam(name = "lemma1", targetNamespace = "")
        String lemma1,
        @WebParam(name = "lemma2", targetNamespace = "")
        String lemma2);

    /**
     * 
     * @param lemma1
     * @param lemma2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSRForPairOfLemmasFast", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetSRForPairOfLemmasFast")
    @ResponseWrapper(localName = "getSRForPairOfLemmasFastResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetSRForPairOfLemmasFastResponse")
    @Action(input = "http://sr.hua.org/SRWS/getSRForPairOfLemmasFastRequest", output = "http://sr.hua.org/SRWS/getSRForPairOfLemmasFastResponse")
    public double getSRForPairOfLemmasFast(
        @WebParam(name = "lemma1", targetNamespace = "")
        String lemma1,
        @WebParam(name = "lemma2", targetNamespace = "")
        String lemma2);

    /**
     * 
     * @param pos1
     * @param pos2
     * @param lemma1
     * @param lemma2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSRForPairOfLemmasPOSFast", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetSRForPairOfLemmasPOSFast")
    @ResponseWrapper(localName = "getSRForPairOfLemmasPOSFastResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetSRForPairOfLemmasPOSFastResponse")
    @Action(input = "http://sr.hua.org/SRWS/getSRForPairOfLemmasPOSFastRequest", output = "http://sr.hua.org/SRWS/getSRForPairOfLemmasPOSFastResponse")
    public double getSRForPairOfLemmasPOSFast(
        @WebParam(name = "lemma1", targetNamespace = "")
        String lemma1,
        @WebParam(name = "lemma2", targetNamespace = "")
        String lemma2,
        @WebParam(name = "pos1", targetNamespace = "")
        String pos1,
        @WebParam(name = "pos2", targetNamespace = "")
        String pos2);

    /**
     * 
     * @param t2
     * @param o2
     * @param t1
     * @param o1
     * @param p2
     * @param p1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateSR", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.CalculateSR")
    @ResponseWrapper(localName = "calculateSRResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.CalculateSRResponse")
    @Action(input = "http://sr.hua.org/SRWS/calculateSRRequest", output = "http://sr.hua.org/SRWS/calculateSRResponse")
    public double calculateSR(
        @WebParam(name = "t1", targetNamespace = "")
        String t1,
        @WebParam(name = "p1", targetNamespace = "")
        int p1,
        @WebParam(name = "o1", targetNamespace = "")
        long o1,
        @WebParam(name = "t2", targetNamespace = "")
        String t2,
        @WebParam(name = "p2", targetNamespace = "")
        int p2,
        @WebParam(name = "o2", targetNamespace = "")
        long o2);

    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lemmatize", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.Lemmatize")
    @ResponseWrapper(localName = "lemmatizeResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.LemmatizeResponse")
    @Action(input = "http://sr.hua.org/SRWS/lemmatizeRequest", output = "http://sr.hua.org/SRWS/lemmatizeResponse")
    public String lemmatize(
        @WebParam(name = "input", targetNamespace = "")
        String input);

    /**
     * 
     * @param t2
     * @param o2
     * @param t1
     * @param o1
     * @param p2
     * @param p1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculatePMI", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.CalculatePMI")
    @ResponseWrapper(localName = "calculatePMIResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.CalculatePMIResponse")
    @Action(input = "http://sr.hua.org/SRWS/calculatePMIRequest", output = "http://sr.hua.org/SRWS/calculatePMIResponse")
    public double calculatePMI(
        @WebParam(name = "t1", targetNamespace = "")
        String t1,
        @WebParam(name = "p1", targetNamespace = "")
        int p1,
        @WebParam(name = "o1", targetNamespace = "")
        long o1,
        @WebParam(name = "t2", targetNamespace = "")
        String t2,
        @WebParam(name = "p2", targetNamespace = "")
        int p2,
        @WebParam(name = "o2", targetNamespace = "")
        long o2);

    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllExtendedGlossPairsForTerms", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllExtendedGlossPairsForTerms")
    @ResponseWrapper(localName = "getAllExtendedGlossPairsForTermsResponse", targetNamespace = "http://sr.hua.org/", className = "de.tu.dresden.quasy.enhancer.omiotis.GetAllExtendedGlossPairsForTermsResponse")
    @Action(input = "http://sr.hua.org/SRWS/getAllExtendedGlossPairsForTermsRequest", output = "http://sr.hua.org/SRWS/getAllExtendedGlossPairsForTermsResponse")
    public String getAllExtendedGlossPairsForTerms(
        @WebParam(name = "input", targetNamespace = "")
        String input);

}
