
package de.tu.dresden.quasy.webservices.omiotis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SRWSService", targetNamespace = "http://sr.hua.org/", wsdlLocation = "http://omiotis.hua.gr/srservice/SRWS?wsdl")
public class SRWSService
    extends Service
{

    private final static URL SRWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SRWSSERVICE_EXCEPTION;
    private final static QName SRWSSERVICE_QNAME = new QName("http://sr.hua.org/", "SRWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://omiotis.hua.gr/srservice/SRWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRWSSERVICE_WSDL_LOCATION = url;
        SRWSSERVICE_EXCEPTION = e;
    }

    public SRWSService() {
        super(__getWsdlLocation(), SRWSSERVICE_QNAME);
    }

    public SRWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRWSSERVICE_QNAME, features);
    }

    public SRWSService(URL wsdlLocation) {
        super(wsdlLocation, SRWSSERVICE_QNAME);
    }

    public SRWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRWSSERVICE_QNAME, features);
    }

    public SRWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SRWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SRWS
     */
    @WebEndpoint(name = "SRWSPort")
    public SRWS getSRWSPort() {
        return super.getPort(new QName("http://sr.hua.org/", "SRWSPort"), SRWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SRWS
     */
    @WebEndpoint(name = "SRWSPort")
    public SRWS getSRWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sr.hua.org/", "SRWSPort"), SRWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRWSSERVICE_EXCEPTION!= null) {
            throw SRWSSERVICE_EXCEPTION;
        }
        return SRWSSERVICE_WSDL_LOCATION;
    }

}
